package com.example.greenDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;


import com.example.greenBean.CountryBean;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table COUNTRY_BEAN.
*/
public class CountryBeanDao extends AbstractDao<CountryBean, String> {

    public static final String TABLENAME = "COUNTRY_BEAN";

    /**
     * Properties of entity CountryBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property CountryName = new Property(0, String.class, "CountryName", true, "COUNTRY_NAME");
    };


    public CountryBeanDao(DaoConfig config) {
        super(config);
    }
    
    public CountryBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'COUNTRY_BEAN' (" + //
                "'COUNTRY_NAME' TEXT PRIMARY KEY NOT NULL );"); // 0: CountryName
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'COUNTRY_BEAN'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, CountryBean entity) {
        stmt.clearBindings();
 
        String CountryName = entity.getCountryName();
        if (CountryName != null) {
            stmt.bindString(1, CountryName);
        }
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public CountryBean readEntity(Cursor cursor, int offset) {
        CountryBean entity = new CountryBean( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0) // CountryName
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, CountryBean entity, int offset) {
        entity.setCountryName(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(CountryBean entity, long rowId) {
        return entity.getCountryName();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(CountryBean entity) {
        if(entity != null) {
            return entity.getCountryName();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
