package com.example.greendao_fc;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CACHE_BEAN1.
 */
public class CacheBean1 {

    private String JsonKey;
    private String JsonCache;
    private Long time;

    public CacheBean1() {
    }

    public CacheBean1(String JsonKey) {
        this.JsonKey = JsonKey;
    }

    public CacheBean1(String JsonKey, String JsonCache, Long time) {
        this.JsonKey = JsonKey;
        this.JsonCache = JsonCache;
        this.time = time;
    }

    public String getJsonKey() {
        return JsonKey;
    }

    public void setJsonKey(String JsonKey) {
        this.JsonKey = JsonKey;
    }

    public String getJsonCache() {
        return JsonCache;
    }

    public void setJsonCache(String JsonCache) {
        this.JsonCache = JsonCache;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

}
