package com.example.greendao_fc;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.greendao_fc.CacheBean1;

import com.example.greendao_fc.CacheBean1Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cacheBean1DaoConfig;

    private final CacheBean1Dao cacheBean1Dao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cacheBean1DaoConfig = daoConfigMap.get(CacheBean1Dao.class).clone();
        cacheBean1DaoConfig.initIdentityScope(type);

        cacheBean1Dao = new CacheBean1Dao(cacheBean1DaoConfig, this);

        registerDao(CacheBean1.class, cacheBean1Dao);
    }
    
    public void clear() {
        cacheBean1DaoConfig.getIdentityScope().clear();
    }

    public CacheBean1Dao getCacheBean1Dao() {
        return cacheBean1Dao;
    }

}
