package com.example.greenBean;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END


import com.example.Bean.BaseBean;

/**
 * Entity mapped to table BONDED_AREA_BEAN.
 */
public class BondedAreaBean extends BaseBean {

    private String BondedAreaName;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public BondedAreaBean() {
    }

    public BondedAreaBean(String BondedAreaName) {
        this.BondedAreaName = BondedAreaName;
    }

    public String getBondedAreaName() {
        return BondedAreaName;
    }

    public void setBondedAreaName(String BondedAreaName) {
        this.BondedAreaName = BondedAreaName;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
