package com.example.greenBean;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END


import com.example.Bean.BaseBean;

/**
 * Entity mapped to table CACHE_BEAN.
 */
public class CacheBean extends BaseBean {

    private String JsonKey;
    private String JsonContent;
    private String CacheTime;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public CacheBean() {
    }

    public CacheBean(String JsonKey, String JsonContent, String CacheTime) {
        this.JsonKey = JsonKey;
        this.JsonContent = JsonContent;
        this.CacheTime = CacheTime;
    }

    public String getJsonKey() {
        return JsonKey;
    }

    public void setJsonKey(String JsonKey) {
        this.JsonKey = JsonKey;
    }

    public String getJsonContent() {
        return JsonContent;
    }

    public void setJsonContent(String JsonContent) {
        this.JsonContent = JsonContent;
    }

    public String getCacheTime() {
        return CacheTime;
    }

    public void setCacheTime(String CacheTime) {
        this.CacheTime = CacheTime;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
