package com.example.greenBean;


// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import com.example.Bean.BaseBean;

/**
 * Entity mapped to table CATEGORY_DETAIL_BEAN.
 */
public class CategoryDetailBean extends BaseBean {

    private String CategoryID;
    private String CategoryDes;
    private String CategoryName;
    private String Img;
    private String IsShow;
    private String Orders;
    private String ParentID;
    private String rootID;
    private String SortOrder;
    //选中的标识
    private boolean isselected=false;

    public boolean isIsselected() {
        return isselected;
    }

    public void setIsselected(boolean isselected) {
        this.isselected = isselected;
    }
    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public CategoryDetailBean() {
    }

    public CategoryDetailBean(String CategoryID) {
        this.CategoryID = CategoryID;
    }

    public CategoryDetailBean(String CategoryID, String CategoryDes,
                              String CategoryName, String Img, String IsShow, String Orders,
                              String ParentID, String rootID, String SortOrder) {
        this.CategoryID = CategoryID;
        this.CategoryDes = CategoryDes;
        this.CategoryName = CategoryName;
        this.Img = Img;
        this.IsShow = IsShow;
        this.Orders = Orders;
        this.ParentID = ParentID;
        this.rootID = rootID;
        this.SortOrder = SortOrder;
    }

    public String getCategoryID() {
        return CategoryID;
    }

    public void setCategoryID(String CategoryID) {
        this.CategoryID = CategoryID;
    }

    public String getCategoryDes() {
        return CategoryDes;
    }

    public void setCategoryDes(String CategoryDes) {
        this.CategoryDes = CategoryDes;
    }

    public String getCategoryName() {
        return CategoryName;
    }

    public void setCategoryName(String CategoryName) {
        this.CategoryName = CategoryName;
    }

    public String getImg() {
        return Img;
    }

    public void setImg(String Img) {
        this.Img = Img;
    }

    public String getIsShow() {
        return IsShow;
    }

    public void setIsShow(String IsShow) {
        this.IsShow = IsShow;
    }

    public String getOrders() {
        return Orders;
    }

    public void setOrders(String Orders) {
        this.Orders = Orders;
    }

    public String getParentID() {
        return ParentID;
    }

    public void setParentID(String ParentID) {
        this.ParentID = ParentID;
    }

    public String getRootID() {
        return rootID;
    }

    public void setRootID(String rootID) {
        this.rootID = rootID;
    }

    public String getSortOrder() {
        return SortOrder;
    }

    public void setSortOrder(String SortOrder) {
        this.SortOrder = SortOrder;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
