package com.example.greenBean;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END


import com.example.Bean.BaseBean;

/**
 * Entity mapped to table COUNTRY_BEAN.
 */
public class CountryBean extends BaseBean {

    private String CountryName;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public CountryBean() {
    }

    public CountryBean(String CountryName) {
        this.CountryName = CountryName;
    }

    public String getCountryName() {
        return CountryName;
    }

    public void setCountryName(String CountryName) {
        this.CountryName = CountryName;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
