package com.example.greenBean;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END


import com.example.Bean.BaseBean;

/**
 * Entity mapped to table STRATEGY_GROUP_BEAN.
 */
public class StrategyGroupBean extends BaseBean {

    private String GroupId;
    private String SelectedImage;
    private String Description;
    private String GroupName;
    private String SortIndex;
    private String Image;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public StrategyGroupBean() {
    }

    public StrategyGroupBean(String GroupId) {
        this.GroupId = GroupId;
    }

    public StrategyGroupBean(String GroupId, String SelectedImage, String Description, String GroupName, String SortIndex, String Image) {
        this.GroupId = GroupId;
        this.SelectedImage = SelectedImage;
        this.Description = Description;
        this.GroupName = GroupName;
        this.SortIndex = SortIndex;
        this.Image = Image;
    }

    public String getGroupId() {
        return GroupId;
    }

    public void setGroupId(String GroupId) {
        this.GroupId = GroupId;
    }

    public String getSelectedImage() {
        return SelectedImage;
    }

    public void setSelectedImage(String SelectedImage) {
        this.SelectedImage = SelectedImage;
    }

    public String getDescription() {
        return Description;
    }

    public void setDescription(String Description) {
        this.Description = Description;
    }

    public String getGroupName() {
        return GroupName;
    }

    public void setGroupName(String GroupName) {
        this.GroupName = GroupName;
    }

    public String getSortIndex() {
        return SortIndex;
    }

    public void setSortIndex(String SortIndex) {
        this.SortIndex = SortIndex;
    }

    public String getImage() {
        return Image;
    }

    public void setImage(String Image) {
        this.Image = Image;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
